---
- name: Upgrade Kubernetes Kubeadm Cluster - Masters
  hosts: masters
  become: yes
  serial: 1  # Run on one master at a time
  vars:
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  roles:
    - { role: upgrade-masters, when: "'masters' in group_names" }

- name: Upgrade Kubernetes Kubeadm Cluster - Workers
  hosts: workers
  become: yes
  serial: 1  # Run on one master at a time
  vars:
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  roles:
    - { role: upgrade-workers, when: "'workers' in group_names" }
